export const QUEUE_NAMES = {
  WHATSAPP_MESSAGES: 'whatsapp-messages',
  FOLLOW_UP_SCAN: 'follow-up-scan',
  PAYMENT_EVENTS: 'payment-events',
} as const;

export const MESSAGE_DIRECTION = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;

export const MESSAGE_STATUS = {
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
} as const;

/** Phase 8 — the AI agent's own sentiment assessment for a turn, computed
 * during the conversation (no separate analysis pass). */
export const MESSAGE_SENTIMENT = {
  POSITIVE: 'POSITIVE',
  NEUTRAL: 'NEUTRAL',
  FRUSTRATED: 'FRUSTRATED',
} as const;

export const CONVERSATION_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED',
  CLOSED: 'CLOSED',
} as const;

export const EVENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
} as const;

export const EVENT_TYPE = {
  MESSAGE: 'message',
  STATUS: 'status',
  CHANGE: 'change',
} as const;

export const ORDER_STATUS = {
  DRAFT: 'DRAFT',
  PLACED: 'PLACED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  FULFILLING: 'FULFILLING',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;

export const PAYMENT_PROVIDER = {
  PAYSTACK: 'PAYSTACK',
} as const;

/** Manual delivery lifecycle (Phase 7): PROCESSING after payment, then shipped, then delivered. */
export const DELIVERY_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
} as const;

export const FOLLOWUP_TYPE = {
  CART: 'CART',
  PAYMENT: 'PAYMENT',
} as const;

export const FOLLOWUP_STATUS = {
  SENDING: 'SENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
} as const;

export const AGENT_ROLE = {
  SALES: 'sales',
  SUPPORT: 'support',
  LOGISTICS: 'logistics',
} as const;

export const ESCALATION_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
} as const;

export const ESCALATION_CATEGORY = {
  ANGRY_CUSTOMER: 'ANGRY_CUSTOMER',
  REFUND_REQUEST: 'REFUND_REQUEST',
  AGENT_UNCERTAIN: 'AGENT_UNCERTAIN',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',
  OTHER: 'OTHER',
} as const;

export const AUDIT_ACTOR = {
  SYSTEM: 'SYSTEM',
  AI_AGENT: 'AI_AGENT',
  OWNER: 'OWNER',
  CUSTOMER: 'CUSTOMER',
  WEBHOOK: 'WEBHOOK',
} as const;

export const AUDIT_ACTIONS = {
  WEBHOOK_EVENT_RECEIVED: 'WEBHOOK_EVENT_RECEIVED',
  WEBHOOK_EVENT_FAILED: 'WEBHOOK_EVENT_FAILED',
  MESSAGE_INGESTED: 'MESSAGE_INGESTED',
  MESSAGE_INGEST_FAILED: 'MESSAGE_INGEST_FAILED',
  MESSAGE_STATUS_UPDATED: 'MESSAGE_STATUS_UPDATED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  VOICE_NOTE_TRANSCRIBED: 'VOICE_NOTE_TRANSCRIBED',
  CATALOG_GENERATED: 'CATALOG_GENERATED',
  CATALOG_IMAGE_REJECTED: 'CATALOG_IMAGE_REJECTED',
  CATALOG_REVIEWED: 'CATALOG_REVIEWED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  ORDER_CREATED: 'ORDER_CREATED',
  STOCK_RESERVED: 'STOCK_RESERVED',
  STOCK_DEDUCTED: 'STOCK_DEDUCTED',
  PAYMENT_LINK_CREATED: 'PAYMENT_LINK_CREATED',
  PAYMENT_WEBHOOK_RECEIVED: 'PAYMENT_WEBHOOK_RECEIVED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_CONFIRMATION_SENT: 'PAYMENT_CONFIRMATION_SENT',
  STOCK_RACE_CONFLICT: 'STOCK_RACE_CONFLICT',
  DELIVERY_STATUS_UPDATED: 'DELIVERY_STATUS_UPDATED',
  ESCALATED_TO_HUMAN: 'ESCALATED_TO_HUMAN',
  ESCALATION_CREATED: 'ESCALATION_CREATED',
  DELIVERY_ADDRESS_UPDATED: 'DELIVERY_ADDRESS_UPDATED',
  FOLLOW_UP_SENT: 'FOLLOW_UP_SENT',
  ORDER_ATTRIBUTED_TO_FOLLOW_UP: 'ORDER_ATTRIBUTED_TO_FOLLOW_UP',
} as const;
