/**
 * NAYAYA & CO. brand system — the SINGLE source of truth for brand tokens.
 *
 * Rule: no hex color value may live outside this file. Every component
 * references these tokens (or the CSS custom properties generated by
 * `brandCssVars`), so a rebrand is a one-file change.
 */

const brandColors = {
  /** Deep Terracotta — logo, headers, primary buttons. */
  primary: '#B55A3A',
  /** Slightly darker terracotta for primary-button hover. */
  primaryHover: '#9E4B2F',
  /** Text on top of primary-colored surfaces. */
  onPrimary: '#FFFFFF',
  /** Warm Charcoal — text, dark backgrounds. */
  secondary: '#2B2622',
  /** Antique Gold — "& CO." lettering, highlights, borders. */
  accent: '#C9A66B',
  /** Warm Ivory — page/catalog backgrounds. */
  base: '#F5EFE6',
  /** Ivory-white surface for cards/panels (derived from base). */
  surface: '#FFFBF5',
  /** Body text (same family as secondary; semantic alias). */
  ink: '#2B2622',
  /** Secondary text — warm taupe (derived from the palette). */
  muted: '#8A7A68',
  /** Hairline borders — warm sand (derived from accent). */
  line: '#E5D8C4',
  /** Sentiment chip: positive — muted sage (derived from the palette). */
  positive: '#3F7A4E',
  positiveBg: '#E4EFE3',
  /** Sentiment chip: frustrated — deep terracotta red. */
  frustrated: '#A94E3A',
  frustratedBg: '#F5E2DA',
  /** Sentiment chip: neutral — warm taupe. */
  neutral: '#7A6E5F',
  neutralBg: '#ECE5D9',
} as const;

const brandFonts = {
  /** Serif for logo + headings — signals "established/heritage" ("& Co."). */
  serif: `'Playfair Display', 'Cormorant Garamond', Georgia, 'Times New Roman', serif`,
  /** Sans for body text — readable on mobile. */
  sans: `'Inter', 'Montserrat', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`,
  /** Google Fonts stylesheet that ships both families. */
  googleStylesheet:
    'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap',
} as const;

const brandSpacing = {
  xs: '4px',
  sm: '8px',
  md: '12px',
  lg: '16px',
  xl: '24px',
  xxl: '32px',
} as const;

/** Stacked logo lockup (NAYAYA / & CO. / rule / tagline) — dashboard header. */
function buildLockup(): string {
  const { primary, accent, secondary } = brandColors;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 96" role="img" aria-label="NAYAYA &amp; CO. — Everything Home. One Name.">
  <text x="170" y="46" text-anchor="middle" font-family="${brandFonts.serif}" font-size="40" font-weight="700" letter-spacing="8" fill="${primary}">NAYAYA</text>
  <text x="170" y="68" text-anchor="middle" font-family="${brandFonts.serif}" font-size="15" letter-spacing="5" fill="${accent}">&amp; CO.</text>
  <line x1="55" y1="76" x2="285" y2="76" stroke="${accent}" stroke-width="1"/>
  <text x="170" y="91" text-anchor="middle" font-family="${brandFonts.sans}" font-size="9" letter-spacing="3.5" fill="${secondary}">EVERYTHING HOME · ONE NAME</text>
</svg>`;
}

/** Minimal square mark (terracotta tile + gold line-drawn picture frame) — favicon. */
function buildMark(): string {
  const { primary, accent } = brandColors;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect x="2" y="2" width="60" height="60" rx="12" fill="${primary}"/>
  <rect x="16" y="16" width="32" height="32" rx="2" fill="none" stroke="${accent}" stroke-width="3.5"/>
  <polygon points="23,42 34,26 45,42" fill="${accent}"/>
</svg>`;
}

export const brand = {
  name: 'NAYAYA & CO.',
  tagline: 'Everything Home. One Name.',
  colors: brandColors,
  fonts: brandFonts,
  spacing: brandSpacing,
  logo: {
    lockupSvg: buildLockup(),
    faviconSvg: buildMark(),
  },
} as const;

/** CSS custom properties for the whole palette, generated from the tokens. */
export function brandCssVars(): string {
  const c = brand.colors;
  const s = brand.spacing;
  return [
    `--brand-primary: ${c.primary};`,
    `--brand-primary-hover: ${c.primaryHover};`,
    `--brand-on-primary: ${c.onPrimary};`,
    `--brand-secondary: ${c.secondary};`,
    `--brand-accent: ${c.accent};`,
    `--brand-base: ${c.base};`,
    `--brand-surface: ${c.surface};`,
    `--brand-ink: ${c.ink};`,
    `--brand-muted: ${c.muted};`,
    `--brand-line: ${c.line};`,
    `--brand-positive: ${c.positive};`,
    `--brand-positive-bg: ${c.positiveBg};`,
    `--brand-frustrated: ${c.frustrated};`,
    `--brand-frustrated-bg: ${c.frustratedBg};`,
    `--brand-neutral: ${c.neutral};`,
    `--brand-neutral-bg: ${c.neutralBg};`,
    `--brand-serif: ${brand.fonts.serif};`,
    `--brand-sans: ${brand.fonts.sans};`,
    `--brand-space-xs: ${s.xs};`,
    `--brand-space-sm: ${s.sm};`,
    `--brand-space-md: ${s.md};`,
    `--brand-space-lg: ${s.lg};`,
    `--brand-space-xl: ${s.xl};`,
    `--brand-space-xxl: ${s.xxl};`,
  ].join('\n');
}

/** Data-URI favicon built from the brand mark. */
export function faviconDataUri(): string {
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(brand.logo.faviconSvg)}`;
}